classdef RandomPWANetwork < PWANetwork
    %PWANetwork Summary of this class goes here
    %   Detailed explanation goes here
    
    
    methods(Access = public)
        function obj = RandomPWANetwork(n_inputs, hidden_neurons, varargin)
            %RandomPWANetwork Construct an instance of this class
            neurons = [n_inputs ; hidden_neurons(:)];

            for i = 1:length(neurons)-2
                random_layers(i) = struct(               ...
                    'type', 'dense',                     ...
                    'activation', 'relu',                ...
                    'W', randn(neurons(i+1),neurons(i)), ...
                    'b', randn(neurons(i+1),1)           ...
                );
            end
            random_layers(end+1) = struct(               ...
                'type', 'dense',                     ...
                'activation', 'none',                ...
                'W', randn(neurons(end),neurons(end-1)), ...
                'b', randn(neurons(end),1)           ...
            );
            obj = obj@PWANetwork(random_layers);                           
        end
    end
end

